image: rocker/verse:4.4.1

pages:
  stage: deploy
  before_script:
   # Install Quarto
  - wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.57/quarto-1.5.57-linux-amd64.deb
  - sudo dpkg -i quarto-1.5.57-linux-amd64.deb
  - quarto check install  
  # R packages
  - R -e "install.packages('remotes')" 
  - R -e "remotes::install_version('quarto',version = '1.4')" 
  - R -e "remotes::install_version('collapsibleTree',version = '0.1.8')"   
  - R -e "remotes::install_version('kableExtra', version = '1.4.0')" 
  - R -e "remotes::install_version('openxlsx',version = '4.2.5.2')" 
  - R -e "remotes::install_version('crosstalk', version = '1.2.1')" 
  - R -e "remotes::install_version('DT', version = '0.32')"   
  
    
  script: 
  - mkdir public
  - cp -r ./ORD_index/Images* public/
  - R -e "quarto::quarto_render(); sessionInfo()"       
  - mkdir public
  - mv ./_site/* ./public/  
  

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
