image: registry.gitlab.com/quarto-forge/docker/rstats

pages:
  stage: deploy
  before_script: 
    
  script:
  - R -e "quarto::render_site('Docs')"
  - cp Docs/_site/* public


        

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
