image: rocker/verse:4.2

pages:
  stage: deploy
  before_script:

  script: 
  - R -e "quarto::quarto_render(input= 'Docs')"        

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
