image: rocker/verse:4.2

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto')"
  - R -e "install.packages('tidyverse')"
  - R -e "install.packages('palmerpenguins')"

  script: 
  - cd Docs
  - R -e "quarto::quarto_render()"
  - mv Docs/_site public


        

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
