image: rocker/verse:latest

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto', repos='http://cran.us.r-project.org', dependencies=TRUE)" 
  - R -e "install.packages('collapsibleTree', repos='http://cran.us.r-project.org', dependencies=TRUE)"   
  - R -e "install.packages('pak', repos='http://cran.us.r-project.org', dependencies=TRUE)" 
  - R -e "install.packages('crosstalk', repos='http://cran.us.r-project.org', dependencies=TRUE)" 
  - R -e "install.packages('DT', repos='http://cran.us.r-project.org', dependencies=TRUE)" 
  - R -e "getwd()"
  - mkdir -p public/
  - cp -r ./Docs/contents/ORD_index/Images* public/
    
  script: 
  - cd Docs
  - R -e "quarto::quarto_render()"       
  - mv ./_site/* ../public/  
  

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
