image: rocker/verse:4.3

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto')" 
  - quarto add quarto-ext/shinylive

    
  script: 
  - cd Docs
  - R -e "quarto::quarto_version()"
  - R -e "quarto::quarto_render()"       
  - mv ./_site/* ../public/
  

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
