image: rocker/verse:4.3

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto')" 
  - R -e "install.packages('collapsibleTree')"   
  - R -e "install.packages('pak')" 
  - R -e "pak::pak('posit-dev/r-shinylive')"   
 
    
  script: 
  - cd Docs
  - R -e "quarto::quarto_version()"
  - R -e "quarto::quarto_render()"       
  - mv ./_site/* ../public/
  - mv ./_freeze/* ../public/
  

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
