image: rocker/verse:4.0.0

pages:
  stage: deploy
  before_script:
    
  script:
  - cp Scripts/affordLogo.png public/affordLogo.png
  - cp Scripts/styles.css public/styles.css
  - R -e "rmarkdown::render_site('Scripts/index.Rmd')"
  - mv -r Scripts/public public


        

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
