image: rocker/verse:4.0.0

pages:
  stage: deploy
  before_script:
    
  script:
  - cp Scripts/logo.png public/logo.png
  - cp Scripts/styles.css public/styles.css
  - R -e "rmarkdown::render_site(Scripts/_site.yml)"
        

  artifacts:    
    paths:
    - public    
    
    
  only:
  - master
  interruptible: true
