image: rocker/verse:4.2

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto')"
  - R -e "install.packages('tidyverse')"
  - R -e "install.packages('palmerpenguins')"

  script: 
  - R -e "rmarkdown::render_site()"
  - mv Docs/* public


        

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
