image: rocker/verse:4.2

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto', version = '1.3')"
    
  script: 
  - cd Docs
  - R -e "quarto::quarto_version()"
  - R -e "quarto::quarto_render()"       
  - mv ./_site/* ../public/
  

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
