image: rocker/verse:4.3

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto')" 
  - R -e "install.packages('collapsibleTree')"   
  - R -e "install.packages('pak')" 
  - R -e "install.packages('crosstalk')" 
  - R -e "install.packages('DT')" 
  - R -e "getwd()"
  - mkdir -p public/contents/ORD_index/Images
  - cp -r ./Docs/contents/ORD_index/Images* public/contents/ORD_index/Images 
 
    
  script: 
  - cd Docs
  - R -e "baseDir<- getwd(); quarto::quarto_render()"       
  - mv ./_site/* ../public/  
  

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
