image: rocker/verse:4.3

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto', repos='https://stat.ethz.ch/CRAN/')" 
  - R -e "install.packages('collapsibleTree', repos='https://stat.ethz.ch/CRAN/')"   
  - R -e "install.packages('kableExtra', repos='https://stat.ethz.ch/CRAN/')" 
  - R -e "install.packages('openxlsx', repos='https://stat.ethz.ch/CRAN/')" 
  - R -e "install.packages('crosstalk', repos='https://stat.ethz.ch/CRAN/')" 
  - R -e "install.packages('DT', repos='https://stat.ethz.ch/CRAN/')" 
  - R -e "getwd()"
  - mkdir -p public/
  - cp -r ./Docs/contents/ORD_index/Images* public/
    
  script: 
  - cd Docs
  - R -e "quarto::quarto_render(); sessionInfo()"       
  - mv ./_site/* ../public/  
  

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
