image: rocker/verse:4.0.0

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto')"
    
  script:
  - R -e "quarto::render_site('Docs')"
  - cp Docs/_site/* public


        

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
