image: rocker/verse:4.0.0

pages:
  stage: deploy
  before_script:
    
  script:
  - R -e "baseDir <- getwd(); rmarkdown::render('index.qmd', output_file = file.path(baseDir,'public','index.html'))"
        

  artifacts:    
    paths:
    - public    
    
    
  only:
  - master
  interruptible: true
