image: rocker/verse:4.2

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto')"
  
  script: 
  - cd Docs
  - pwd
  - ls -R
  - R -e "quarto::quarto_render()"       
  

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
