image: rocker/verse:4.0.0

pages:
  stage: deploy
  before_script:
    
  script:
  - R -e "rmarkdown::render_site()"
        

  artifacts:    
    paths:
    - public    
    
    
  only:
  - master
  interruptible: true
