image: rocker/verse:4.2

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto')"

  script: 
  - R -e "packageVersion('quarto')"
  - R -e "rmarkdown::render_site(input = 'Docs')"
  - mv Docs/* public


        

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
