image: rocker/verse:4.2

pages:
  stage: deploy
  before_script:
  - R -e "install.packages('quarto')"

  script:
  - cd Docs
  - R -e "rmarkdown::render_site()"
  - mv Docs/* public


        

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
