image: registry.gitlab.com/quarto-forge/docker/quarto


pages:
  stage: deploy
  before_script: 
    
  script:
  - quarto render Docs --execute --to html --output-dir public  
  - cp Docs/_site/* public


        

  artifacts:    
    paths:
    - public
    
    
  only:
  - master
  interruptible: true
