---
title: Resource Monitoring Protocol
subtitle: Example of a resource monitoring protocol for data stewards and researchers 
date-modified: last-modified
---

# Insights from AFFORD

The following recommendatiosn were derived after a first attempt to keep a time log the activities during data-intensive data collection waves at different facilities.

| Recommendation | Details |
|---------------------|---------------------------------------------------|
| Consistency and precision of measurement units | Use hours (e.g., 1:15 = 1 h 15 min) instead of days as a time tracking unit to avoid ambiguity. |
| Reporting of Waiting Times | Limit the entries to *computing* or *active* work times. Promote centralized services for IT-related tasks. |
| Data Volume | Include estimates of data volume to clarify time estimates for certain tasks like making backups. |
| Retrospective and Prospective Times | Distinguish between *retrospective* vs *prospective* time estimates to improve analysis of activities. |
| Single Resource Monitoring Table | The table should include all relevant governance information e.g.,: Partner, Collaborator, Year |
| Generic Variable Names | Replace specific terms for variable names (e.g., Synchrotron, Beamline) with generic names that can apply to different data modalities (e.g., Facility_1, Facility_2). |
| Codebook | MUST include a "codebook" describing variables, clarify abbreviations and specifying controlled vocabularies. |

: Recommendations {.striped}


# Controlled Vocabularies

| Variable | Categories or Actions |
|---------------|---------------------------------------------------------|
| Purpose | **Data and File Management**: Data acquisition, backups, and archiving, often during data collection. |
|  | **Internal Data Documentation**: Internal documentation with minimal curation for sharing. |
|  | **Data Sharing and Publishing**: Documenting, sharing, and publishing data, including planning and workflow discussions. |
|  | **Data Stewardship**: Assisting researchers with open research data activities. |
|  | **Supporting Documentation**: Creating and publishing tutorials, guides, and how-tos for collaborators or a wider audience. |
| Actions | **Data and File Management**: Research tools, Fix, Download, Backup (*Subactions*: to tape, disk, or server), Archive, Setup. |
|  | **Internal Data Documentation**: Metadata creation/editing, Documentation (*Subactions*: Procedures, Glossary, Codebook, etc.). |
|  | **Data Sharing and Publishing**: Research tools, Decision making, Metadata editing, Documentation, Data index, GitLab setup. |
|  | **Data Stewardship**: Define FAIR goals, Project examination, FAIR cycles, Post-FAIR reviews. |
|  | **Supporting Documentation**: Research, Write, Publish, Stakeholder assessment. |

: Vocabulary {.striped}



