project:
  type: website
  output-dir: docs


website:
  title: "AFFORD_docsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Welcome.md
      - Tutorials.md      

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual