project:
  type: website


website:
  title: "AFFORD tutorials"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: Welcome.md
      - text: "Tutorials"
        file: Tutorials.md
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://gitlab.uzh.ch/crsuzh/AFFORD_tutorials        

  sidebar:
    style: "docked"
    background: light
    search: true
    contents:
      - section: "Home"
        contents:
          - Welcome.md
          
      - section: "Tutorials"
        contents:
          - Tutorial-0.-Main-workflow.md
          - Tutorial-1.-Using-Gitlab-for-Project-Owners-and-Collaborators.md
          - Tutorial-2.-Creating-and-Updating-a-Data-Hub-in-Gitlab.md
          - Tutorial-3.-Customizing-Gitlab-Continuous-Integration.md
    
    

format:
  html:
    theme: minty
    toc: true
    code-copy: false

editor: visual
