project:
  type: website
            
website:
    title: Home
    page-navigation: true
    back-to-top-navigation: true
    page-footer:
        left: |
          Created by the [Center for Reproducible Science](https://www.crs.uzh.ch/en.html) of the [University of Zurich](https://www.uzh.ch/de.html). Go to [Gitlab repo](https://gitlab.uzh.ch/crsuzh/AFFORD_website)
        center: |
            [About Us](contents/about/index.html)
        right: |
           This is a free website under the [CC BY international license 4.0 ](https://creativecommons.org/licenses/by/4.0/). 
           
           
    favicon:  assets/logos/Logo_CRS_col.svg
    
    site-url: https://crsuzh.pages.uzh.ch/AFFORD_website/
    repo-url: https://gitlab.uzh.ch/crsuzh/AFFORD_website 
       
    
    navbar:        
        logo:  assets/logos/Logo_AFFORD_col.svg    
        background: '#1e5e50'  #light
        collapse-below: lg
                    
        right:                  
          - text: "Data Index"            
            href: contents/ORD_index/index.qmd
          - text: "Tutorials"            
            href: contents/tutorials/index.qmd
          - text: "Templates"            
            href: contents/templates/index.qmd
          - text: "Presentations"            
            href: contents/presentations/index.qmd
          - text: "Glossary"            
            href: contents/glossary/index.qmd     
          - text: "Contact"
            href: contents/contact/index.qmd                  
    
    sidebar:          
        - id: Tutorials
          title: "Tutorials"                  
          background:  '#e8faf6'
          style: "docked"       
          #href:  contents/tutorials/index.qmd      
          contents:
            - contents/tutorials/index.qmd            
            - section: "🏷**Documentation & Metadata**"    
              contents:                 
                - contents/tutorials/Tutorial_Metadata_JSON.qmd                            
                - contents/tutorials/Tutorial_Metadata_tables.qmd                                           
                
            - section: "🔭**Finding, Sharing and Publishing**"      
              contents:
                - contents/tutorials/Tutorial_Gitlab_workflows.qmd
                - contents/tutorials/Tutorial_Gitlab1_IntroGit.qmd                                              
                - contents/tutorials/Tutorial_Gitlab2_DataIndex.qmd                   
                - contents/tutorials/Tutorial_Gitlab3_CI.qmd
                - contents/tutorials/Tutorial_Web.qmd                    
                
           
                 
        - id: "" # leave other sections without sidebar
          title: ""
          
        - id: Templates
          title: "Templates"     
          contents:
                - contents/templates/index.qmd
                - auto: "contents/templates/*.qmd"

format:
    html:         
        grid:
          sidebar-width: 350px
        theme:
            light: cosmo            
        highlight-style: a11y
        code-link: true
        toc: true
        toc-expand: 4
        code-copy: true              
        mermaid: 
          theme: default

freeze: auto

