project:
  type: book

book:
    title: "AFFORD tutorials"
    repo-url: "https://gitlab.uzh.ch/crsuzh/AFFORD_tutorials"
    chapters:
        - index.qmd                
        - part: Tutorials.qmd        
          chapters:
            - Tutorial-0.-Main-workflow.qmd
            - Tutorial-1.-Using-Gitlab-for-Project-Owners-and-Collaborators.qmd
            - Tutorial-2.-Creating-and-Updating-a-Data-Hub-in-Gitlab.qmd
            - Tutorial-3.-Customizing-Gitlab-Continuous-Integration.qmd            
    page-navigation: true

format:
    html:    
        author: Center for Reproducible Science 
        theme:
            light: minty
            dark: solar
        toc: true
        code-copy: false
