project:
  type: website
            
website:
    page-navigation: true
    back-to-top-navigation: true
    page-footer:
        left: |
          Tutorials of the [Center for Reproducible Science](https://www.crs.uzh.ch/en.html) from the University of Zurich.
          
        right: |
           This website is and will always be free, licensed under the [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) License.
           
    
    favicon:  logos/Logo_CRS_col.svg
    
    site-url: https://crsuzh.pages.uzh.ch/AFFORD_tutorials/
    repo-url: https://gitlab.uzh.ch/crsuzh/AFFORD_tutorials 
    
    navbar:
        title: AFFORD Home
        logo:  logos/Logo_AFFORD_col.svg
        right:                  
          - text: Tutorials  
            href: tutorials/Tutorials.qmd                
          - text: Presentations
            href: presentations/Presentations.qmd                
          - text: Reports
            href: reports/Reports.qmd                
            
format:
    html:    
        #author: Center for Reproducible Science 
        theme:
            light:
                - cosmo
                - assets/styles.css
            dark: solar
        highlight-style: a11y
        code-link: true
        toc: true
        code-copy: false
        callout-appearance: simple

