project:
  type: book

book:
    title: "AFFORD tutorials"
    repo-url: "https://gitlab.uzh.ch/crsuzh/AFFORD_tutorials"
    chapters:
        - index.md        
        - Home.md        
        - part: Tutorials.md        
          chapters:
            - Tutorial-0.-Main-workflow.md
            - Tutorial-1.-Using-Gitlab-for-Project-Owners-and-Collaborators.md
            - Tutorial-2.-Creating-and-Updating-a-Data-Hub-in-Gitlab.md
            - Tutorial-3.-Customizing-Gitlab-Continuous-Integration.md
    page-navigation: true

format:
    html:    
        author: Center for Reproducible Science
        theme: minty
        toc: true
        code-copy: false