name: Deploy Quarto site to GitHub Pages
on:
  push:
    branches: [master]

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) install Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # 2) render the site (produces _site/)
      - name: Render Quarto site
        run: quarto render

      # 3) upload that folder as the Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      # 4) deploy the artifact you just uploaded
      - uses: actions/deploy-pages@v2
