name: Deploy Quarto site to GitHub Pages

on:
  push:
    branches:
      - main  # Only build on pushes to main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.6.42

      - name: Install R packages
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_version('kableExtra', version = '1.4.0')"
          Rscript -e "remotes::install_version('crosstalk', version = '1.2.1')"

      - name: Render Quarto site
        run: |
          cd contents
          quarto render
          mkdir -p ../public
          cp -r _book/* ../public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
