name: Quarto Publish

on:
  push:
    branches: [master]   # update if you rename the default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # These permissions are required to push to another branch
    permissions:
      contents: write     # commit to gh-pages
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Install the Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2
        # with:           # optional: pin a version
        #   version: 1.4.552

      # Render the site into _site/
      - name: Render
        run: quarto render

      # Publish everything in _site/ to the gh-pages branch
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages

