name: Quarto Publish

on:
  push:
    branches: [master]          # default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # 1) install R
      - uses: r-lib/actions/setup-r@v2

      # 2) install R + all needed packages
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(
            c("rmarkdown","knitr","dplyr","tidyr","readr","ggplot2",
              "xml2","downlit","crosstalk","DT","openxlsx","collapsibleTree",
              "readxl","kableExtra"),
            repos="https://cloud.r-project.org"
          )'

    
      # 3) install Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2

      # 4) render the site
      - name: Render site
        run: quarto render

      # 5) publish the rendered HTML to gh-pages
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
