name: Quarto Publish

on:
  push:
    branches: [master]      # <- your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # -------- NEW: install R --------
      - uses: r-lib/actions/setup-r@v2     # gets the latest stable R
      # ---------------------------------

      - uses: quarto-dev/quarto-actions/setup@v2   # installs Quarto CLI

      - name: Render site
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages


