name: Deploy Quarto site to GitHub Pages
on:
  push:
    branches: [master]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto site
        run: quarto render   # ← this creates the _site folder

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site        # ← now _site actually exists!

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

